//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tesuri.DevToys.MC_NBFXViewer {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MC_NBFXViewer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MC_NBFXViewer() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tesuri.DevToys.MC_NBFXViewer.MC_NBFXViewer", typeof(MC_NBFXViewer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   MC_NBFX Viewer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddLine {
            get {
                return ResourceManager.GetString("AddLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto recognition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompressModeAuto {
            get {
                return ResourceManager.GetString("CompressModeAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deflate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompressModeDeflate {
            get {
                return ResourceManager.GetString("CompressModeDeflate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GZip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompressModeGZip {
            get {
                return ResourceManager.GetString("CompressModeGZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompressModeNone {
            get {
                return ResourceManager.GetString("CompressModeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Binary XML Viewer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DictionaryKey {
            get {
                return ResourceManager.GetString("DictionaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dictionary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DictionaryTitle {
            get {
                return ResourceManager.GetString("DictionaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DictionaryValue {
            get {
                return ResourceManager.GetString("DictionaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Binary data(Base64 text) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputTitle {
            get {
                return ResourceManager.GetString("InputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MC_NBFX Viewer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputResult {
            get {
                return ResourceManager.GetString("OutputResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveLine {
            get {
                return ResourceManager.GetString("RemoveLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   binary xml nbfx wcf に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchKeywords {
            get {
                return ResourceManager.GetString("SearchKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CompressMode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsCompressModeTitle {
            get {
                return ResourceManager.GetString("SettingsCompressModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsFormatTitle {
            get {
                return ResourceManager.GetString("SettingsFormatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NBFXViewer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use WCF Dic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SwitchWCFMode {
            get {
                return ResourceManager.GetString("SwitchWCFMode", resourceCulture);
            }
        }
    }
}
